[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "gradientgrove"
version = "0.1.3"
authors = [
    {name="Stephen Flood", email="stephen.flood@bridgew.edu"}
]
description = "Python scripts to allow the creation of both documents and slideshow from a single Markdown file, or a Mkdocs project.  Create a markdown file with mkdocs-style admonitions, compile to html, revealjs, latex, and beamer outputs."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0-only"
license-files = ["LICEN[CS]E*"] 

[tool.setuptools.package-data]
gradientgrove = ["gradientgrove.css"]

[project.urls]
Homepage = "https://gradientgrove.com"
Issues = "https://gradientgrove.com"

[project.scripts]
gradientgrove-publish = "gradientgrove.markdown_publish:main"
gradientgrove-pdf-review = "gradientgrove.pdf_review_tool:main"
gradientgrove-latex-to-markdown = "gradientgrove.markdown_ast:latex_to_markdown_main"
